apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revival
  template:
    metadata:
      labels:
        app: revival
    spec:
      containers:
        - name: revival-app
          image: gcr.io/revival-1/revival-app:latest
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: phoenix-credentials
                  key: database_url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: phoenix-credentials
                  key: secret_key_base
