apiVersion: v1
kind: Service
metadata:
  name: app-service
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"websocket-backendconfig"}}'
spec:
  selector:
    app: revival
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
