apiVersion: networking.gke.io/v1beta1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: main-address
    networking.gke.io/managed-certificates: main-certificate
spec:
  backend:
    serviceName: app-service
    servicePort: 80
  redirectToHttps:
    enabled: true
