apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pg-data
    fsType: ext4
