name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-18.04

    container:
      image: elixir:1.11.2-alpine
      env:
        PGUSER: postgres
        PGPASSWORD: duck_duck
        PGHOST: postgres
        PGDATABASE: revival_test

    services:
      postgres:
        image: postgres:13.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: duck_duck
          POSTGRES_DB: revival_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Fetch dependencies
        uses: mix local.hex --force

      - name: Run tests
        run: mix test
